version: "3"
services:
  stim-builder:
    build: .
    image: ashsrobbins/plotly-stim-builder
    container_name: plotly-stim-builder
    ports:
      - "0.0.0.0:8059:8050"
     #  - "127.0.0.1:8051:8050" 
    volumes:
      - ./assets:/home/jovyan/assets
      - ~/.aws/credentials:/home/jovyan/.aws/credentials:ro
     # usernames and passwords
      # - ./users.py:/console/users.py
      # - ./.env:/console/.env
    # create shadows-network if it doesn't exist, must connect all services that need strapi-shadows-db to shadows-network
    #    network_mode: shadows-network
    restart: unless-stopped
